const GET_ESTATES = 'GET_ESTATES';
const GET_ESTATES_SUCCESS = 'GET_ESTATES_SUCCESS';
const GET_ESTATES_FAILURE = 'GET_ESTATES_FAILURE';
const SET_SEARCH_BAR = 'SET_SEARCH_BAR';
const SHOW_SELECTED_ESTATE = 'SHOW_SELECTED_ESTATE';
const DELETE_ESTATE = 'DELETE_ESTATE';
const DELETE_ESTATE_SUCCESS = 'DELETE_ESTATE_SUCCESS';
const DELETE_ESTATE_FAILURE = 'DELETE_ESTATE_FAILURE';
const POST_ESTATE = 'POST_ESTATE';
const POST_ESTATE_SUCCESS = 'POST_ESTATE_SUCCESS';
const POST_ESTATE_FAILURE = 'POST_ESTATE_FAILURE';

export {
  GET_ESTATES,
  GET_ESTATES_SUCCESS,
  GET_ESTATES_FAILURE,
  SET_SEARCH_BAR,
  SHOW_SELECTED_ESTATE,
  DELETE_ESTATE,
  DELETE_ESTATE_SUCCESS,
  DELETE_ESTATE_FAILURE,
  POST_ESTATE,
  POST_ESTATE_SUCCESS,
  POST_ESTATE_FAILURE
};
